<?php

namespace Database\Seeders;

use App\Containers\Authorization\Models\Permission;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PermissionsTableSeeder extends Seeder
{
    public function run()
    {
        $date = date('Y-m-d H:i:s');
        $permissions = [
            [
                'id'         => '1',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'management_user_access',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '2',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'permission_create',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '3',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'permission_update',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '4',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'permission_show',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '5',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'permission_destroy',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '6',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'permission_access',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '7',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'list_permission',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '8',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'role_create',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '9',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'role_update',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '10',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'role_show',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '11',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'role_destroy',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '12',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'role_access',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '13',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'list_role',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '14',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_create',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '15',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_update',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '16',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_show',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '17',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_destroy',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '18',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_access',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '19',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'list_user',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '20',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_folder_create',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '21',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_folder_update',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '22',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_folder_show',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '23',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_folder_destroy',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '24',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_folder_list',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '25',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_file_upload',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '26',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_file_show',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '27',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_file_list',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '28',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_file_update',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '29',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_file_get',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '30',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_file_destroy',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '31',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_zip',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '32',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_share_item',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '33',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_share_item_show',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '34',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_share_item_update',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '35',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_share_item_destroy',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '36',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_folder_restore',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '37',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_file_restore',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '38',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_settings_update',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '39',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_settings_show',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '40',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'management_user_blacklist',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '41',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_folder_get',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '42',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_traffic_show',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '43',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_team_folder_create',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '44',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_team_folder_show',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '45',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_team_folder_list',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '46',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_team_folder_destroy',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '47',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_team_folder_update',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '48',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_team_folder_convert',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '49',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_team_folder_leave',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '50',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_team_invitation_show',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '51',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_team_invitation_update',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '52',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_team_invitation_destroy',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '53',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_team_invitation_list',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '54',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_shared_with_me_browse',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '55',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_team_folder_browse',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '56',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_folder_browse',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '57',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_notification_list',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '58',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_notification_read',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'id'         => '59',
                'uuid'       => Str::uuid(date('YmdHisu')),
                'title'      => 'user_notification_destroy',
                'created_at' => $date,
                'updated_at' => $date,
            ]
        ];

        Permission::insert($permissions);
    }
}