import "./global";
import "./vueCookies";
import "./flatpicker";
import "./bootstrap-vue";
import "./jvector";
import "./masonry";
import "./magnific-popup";
import "./datatable";
import "./select2";
