from dotenv import load_dotenv
import os

load_dotenv()

APP_HOST_NAME= os.getenv("APP_HOST_NAME")
MONGODB_CONNECTION = os.getenv("MONGODB_CONNECTION")
MONGODB_DB = os.getenv("MONGODB_DB")
FLASK_TMP_DIR = os.getenv("FLASK_TMP_DIR")
IPFS_DOMAIN = os.getenv("IPFS_DOMAIN")
LOCAL_IPFS_WEB_DOMAIN = os.getenv("LOCAL_IPFS_WEB_DOMAIN")
NFT_QUANTITY = os.getenv("NFT_QUANTITY")
XRP_HUBSECURE_WALLET = os.getenv("XRP_HUBSECURE_WALLET")
XRP_CLIENT_WALLET = os.getenv("XRP_CLIENT_WALLET")
XRP_TESTNET_URL = os.getenv("XRP_TESTNET_URL")
XRP_TESTNET_EXPLORER = os.getenv("XRP_TESTNET_EXPLORER")
XRP_HUBSECURE_SECRET = os.getenv("XRP_HUBSECURE_SECRET")

XRP_HUBSECURE_SEED = os.getenv("XRP_HUBSECURE_SEED")
XRP_HUBSECURE_SEQ = os.getenv("XRP_HUBSECURE_SEQ")

IDANALYZER_API_KEY = os.getenv("IDANALYZER_API_KEY")